version: "2"

services:
 database:
    image: mysql:5.6
    ports:
      - 3307:3306
    environment:
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_DATABASE: "soccer"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
