version: "3"

services:
  database:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=soccer
    volumes:
      - ./docker/volumes/database/etc/mysql:/etc/mysql/conf.d
      - ./docker/volumes/database-storage:/var/lib/mysql
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - .:/usr/src/app
    ports:
      - 80:80
