version: "2"

services:
  database:
    image: mysql:5.6
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "soccer"
    volumes:
      - ./docker/volumes/database/etc/mysql:/etc/mysql/conf.d
      - ./docker/volumes/database-storage:/var/lib/mysql